### ISSUE TITLE
Freeze when embedded in LazyVStack (iOS14) with 100% CPU usage

### ISSUE THREAD

**Issue by emerabet** [SDWebImage/SDWebImageSwiftUI#121]
Hello,

I tried the example project embedded in Scrollview & LazyVStack instead of the list and the project freeze at startup (100% CPU) on animated tab and freeze after some 'fast' scroll on WebImage tab (100% CPU) on emulator.

I tested to fix the SDWebImage version to: `s.dependency 'SDWebImage', '~> 5.8.3'` without conclusive results.

If i use the native Image component with local image then it's working.

Do you have any idea about this ?

```
func contentView() -> some View {
        ScrollView {
            LazyVStack {
                ForEach(imageURLs, id: \.self) { url in
                    NavigationLink(destination: DetailView(url: url, animated: self.animated)) {
                        HStack {
                            if self.animated {
                                #if os(macOS) || os(iOS) || os(tvOS)
                                AnimatedImage(url: URL(string:url))
                                    .onViewUpdate { view, context in
                                        #if os(macOS)
                                        view.toolTip = url
                                        #endif
                                    }
                                    .indicator(SDWebImageActivityIndicator.medium)
                                    .transition(.fade)
                                    .resizable()
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                                #else
                                WebImage(url: URL(string:url), isAnimating: self.$animated)
                                    .resizable()
                                    .indicator(.activity)
                                    .transition(.fade(duration: 0.5))
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                                #endif
                            } else {
                                WebImage(url: URL(string:url))
                                    .resizable()
                                    .indicator(.activity)
                                    .transition(.fade(duration: 0.5))
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                            }
                            Text((url as NSString).lastPathComponent)
                        }
                    }
                    .id(UUID())
                    .buttonStyle(PlainButtonStyle())
                }
                .onDelete { indexSet in
                    indexSet.forEach { index in
                        self.imageURLs.remove(at: index)
                    }
                }
            }
        }
    }
```

Thanks !

**Comment by dreampiggy** [comment]
Does normal `VStart`, `HStack` have the same issue ? Not that `LazyVStack`

**Comment by emerabet** [comment]
I can't reproduce the issue with VStack instead of LazyVStack

```
func contentView() -> some View {
        ScrollView {
            VStack {
                ForEach(imageURLs, id: \.self) { url in
                    NavigationLink(destination: DetailView(url: url, animated: self.animated)) {
                        HStack {
                            if self.animated {
                                #if os(macOS) || os(iOS) || os(tvOS)
                                AnimatedImage(url: URL(string:url))
                                    .onViewUpdate { view, context in
                                        #if os(macOS)
                                        view.toolTip = url
                                        #endif
                                    }
                                    .indicator(SDWebImageActivityIndicator.medium)
                                    .transition(.fade)
                                    .resizable()
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                                #else
                                WebImage(url: URL(string:url), isAnimating: self.$animated)
                                    .resizable()
                                    .indicator(.activity)
                                    .transition(.fade(duration: 0.5))
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                                #endif
                            } else {
                                WebImage(url: URL(string:url))
                                    .resizable()
                                    .indicator(.activity)
                                    .transition(.fade(duration: 0.5))
                                    .scaledToFit()
                                    .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                            }
                            Text((url as NSString).lastPathComponent)
                        }
                    }
                    .id(UUID())
                    .buttonStyle(PlainButtonStyle())
                }
                .onDelete { indexSet in
                    indexSet.forEach { index in
                        self.imageURLs.remove(at: index)
                    }
                }
            }
        }
    }
```

**Comment by Dimillian** [comment]
Having same issue. I wonder if it's bug in the implementation of the lazy stacks when you refresh the item once it's been already presented.

**Comment by dreampiggy** [comment]
Need some time to investigate. Can anyone who have time to dive into this ?
I'm busy these days. Maybe have a check in Saturday.

**Comment by Dimillian** [comment]
I’ll take a look when I’m back from vacation if it didn’t progressed. It most probably is a SwiftUI bug as the stack trace is not very actionable. So I would be cautious to not loose too much time on it until later betas.

**Comment by pwightman** [comment]
Also experiencing this issue. I ran it through Instruments but wasn't able to come away with anything very actionable (but I'm also very unfamiliar with the internals of SDWebImage). It wasn't clear to me whether it was a SwiftUI or SDWebImage problem (though the code is definitely recursively calling into SDWebImage). Seemed layout-related, like SDWebImage kept invalidating the layout, causing a recursive reflow by SwiftUI (or something?). Probably wise to wait for at least beta 3 before diving into it too much.

**Comment by pwightman** [comment]
Haven't had a second to try it out yet, but saw this in the beta 3 release notes:

> OnAppear callbacks work reliably in all layouts. (63031598)

Could be related 🤞 I'll give it a go in a bit, unless someone beats me to it.

**Comment by pwightman** [comment]
Appears to be fixed, in my project at least 👍 it was very easy to reproduce before but not able to reproduce it anymore.

**Comment by dreampiggy** [comment]
Does this been fixed by Apple or some View Structure changes ?

I'm busying in this half of month, so I didn't have a check at this issue yet.

**Comment by pwightman** [comment]
Fixed by Apple in beta 3 (as far as I can tell), I think it had something to do with onAppear being called incorrectly (by Apple) for some view types. Maybe wait to hear back from @Dimillian and @emerabet on if they're still experiencing issues, but otherwise I think this issue can be closed.

**Comment by emerabet** [comment]
I was not able to reproduce the problem with the "WebImage" component :) . However, the issue persists with AnimatedImage component (freeze at startup with 100% CPU usage in LazyVStack)

**Comment by mredig** [comment]
I've been running into the same issue myself, but it's inconsistent to reproduce. 

I found that it happened more often if I loaded the same image url multiple times at once (in a LazyHStack), in case that helps at all.

**Comment by Cyclic** [comment]
I'm also running into this issue with LazyHStack. I have a call stack, so I don't know if this helps. I'm running iOS 14 Beta 3 on my physical device. Should I report this to Apple as well?
<img width="1658" alt="hang_crash" src="https://user-images.githubusercontent.com/553800/89136433-94131080-d4e8-11ea-8f2c-52c1ce461408.png">

**Comment by dreampiggy** [comment]
Does this `sd_isVector` check cause some lag ? I doubt this, beucase it's just a NSSelectorFromString method call.

Can you run your App with Instruments Time Profile, to see what cause the CPU hung up ? There are stack to track, also, you can save the Instruments result and upload here to let me analysis.

**Comment by Cyclic** [comment]
I'm not sure if it causes lag, but during a hang, I found it to be one of the active threads. Please find the Time Profiler attached.
[hang3.trace.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/5017251/hang3.trace.zip)

**Comment by kunaltyagi26** [comment]
I am also having this same issue with WebImage embedded in LazyVGrid. I even tried fetching the data inside onAppear() but I am still facing this screen freeze issue with more than 100% CPU usage. Please help if anybody has a solution to this issue. I am adding code as well for reference.

```
struct Home: View {
    @State var expand = false
    @State var search = ""
    @ObservedObject var randomImages = GetData()
    var columns: [GridItem] = Array(repeating: .init(.flexible()), count: 2)
    
    var body: some View {
        VStack(spacing: 0) {
            HStack {
                if !self.expand {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("UnSplash")
                            .font(.title)
                            .fontWeight(.bold)
                        
                        Text("Beautiful, Free Photos")
                            .font(.caption)
                    }
                }
                
                Spacer()
                
                Image(systemName: "magnifyingglass")
                    .foregroundColor(.gray)
                    .onTapGesture {
                        withAnimation(.spring()) {
                            self.expand = true
                        }
                    }
                
                if self.expand {
                    TextField("Search...", text: $search)
                    
                    if self.search != "" {
                        Button(action: {
                            
                        }) {
                            Text("Find")
                                .fontWeight(.bold)
                                .foregroundColor(.black)
                        }
                    }
                    
                    Button(action: {
                        withAnimation(.spring()) {
                            self.expand = false
                        }
                    }) {
                        Image(systemName: "xmark")
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(.black)
                    }
                    .padding(.leading, 10)
                }
            }
            .padding(.top, UIApplication.shared.windows.first?.safeAreaInsets.top)
            .padding()
            .background(Color.white)
            
            if self.randomImages.images.isEmpty {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                ScrollView(.vertical, showsIndicators: false) {
                    LazyVGrid(columns: columns, spacing: 20, content: {
                        ForEach(randomImages.images, id: \.id) { image in
                            WebImage(url: URL(string: image.urls["regular"]!))
                                .resizable()
                                .indicator(.activity)
                                .transition(.fade(duration: 0.5))
                                .scaledToFit()
                        }
                    })
                }
            }
        }
        .background(Color.black.opacity(0.07).edgesIgnoringSafeArea(.all))
        .edgesIgnoringSafeArea(.all)
        .onAppear {
            randomImages.updateData()
        }
    }
}
```
```
class GetData: ObservableObject {
    @Published var images: [Photo] = []
    
    func updateData() {
        let key = "<Your Key>"
        let url = "https://api.unsplash.com/photos/random/?count=30&client_id=\(key)"
        print(url)
        URLSession.shared.dataTask(with: URL(string: url)!) { (data, response, error) in
            if let data = data, error == nil {
                do {
                    let photos = try JSONDecoder().decode([Photo].self, from: data)
                    DispatchQueue.main.async {
                        self.images = photos
                    }
                } catch {
                    print(error.localizedDescription)
                }
            }
        }.resume()
    }
}
```

**Comment by pwightman** [comment]
@kunaltyagi26 is this happening in beta 4 that came out today? Would be nice to confirm, I saw some more notes about `onAppear()` changes in the beta 4 release notes.

**Comment by Rspoon3** [comment]
This is happening for me in beta 4 in a LazyVGrid. I noticed it does not happen if I remove all State and StateObject properties from a view.

**Comment by romabcd** [comment]
I'm seeing the same issue in XCode 12.0.1. Is everyone else still having issues with this?

**Comment by pwightman** [comment]
I've personally not had any issues since whichever beta adjusted the onAppear issues, but I wouldn't be surprised if there's still problems.

**Comment by anonrig** [comment]
I'm experiencing the same issue on tvOS on a scrollview with LazyHStack

**Comment by abbasmousavi** [comment]
I have the same problem on tvOS with Xcode 12.0.1 and LazyVGrid

<img width="1184" alt="Screen Shot 2020-10-11 at 11 44 53 PM" src="https://user-images.githubusercontent.com/1249875/95692082-ef196000-0c1b-11eb-8271-98c394003e0f.png">

**Comment by dreampiggy** [comment]
For the NavigationLink issue, see Readme about **Using Image/WebImage/AnimatedImage in Button/NavigationLink**

https://github.com/SDWebImage/SDWebImageSwiftUI#using-imagewebimageanimatedimage-in-buttonnavigationlink

**Comment by abbasmousavi** [comment]
I am already using `.renderingMode(.original)` but it still crashes

**Comment by dreampiggy** [comment]
What about `.renderingMode(.original)` ?

**Comment by dreampiggy** [comment]
What about `.buttonStyle(PlainButtonStyle())` ?

**Comment by abbasmousavi** [comment]
same, still crashes

**Comment by morad** [comment]
Facing the same problem as well. Using VStack for as it is a short list of items, but it will be a problem later as the list grows.

**Comment by maxtomczyk** [comment]
I can confirm that there is still problem with using LazyVStack, iOS 14,2 (18B92) and XCode 12.2 (12B45b). Is there anything I can do to help you resolve this issue?

**Comment by Jarvey** [comment]
I have this issue when I run my iPad app on a Mac with Catalyst

**Comment by r3pps** [comment]
I had a similar issue to this as well, for me, I had a simple scrollview with LazyVStack to build a social media timeline, and the images were being cached with Nuke. I would reach 100% CPU usage after scrolling just a few times. After following the stack trace, I noticed that I was using a nested regular VStack that contained my image. When I changed this to LazyVStack as well, it fixed my problem.

**Comment by chrisperkins** [comment]
I had a similar issue using a LazyVGrid with the image in a ZStack. The issue was resolved when the ZStack was removed.

**Comment by wilg** [comment]
Having this issue also...

**Comment by r3pps** [comment]
@wilg Did you see my reply? Check if you are using any nested HStacks or VStack within the LazyHstack, LazyVstack. And change them to lazy as well

**Comment by wilg** [comment]
@r3pps How could I possibly avoid using HStacks or VStacks within the Lazy stacks? They're used everywhere in SwiftUI?

**Comment by r3pps** [comment]
@wilg Maybe I didnt explain this well enough, Ill give an example. For me, I was using LazyVStack to generate rows for a social media feed. Each row view contained a nested regular VStack that contained the profile image which was being loaded from the cache/remotely. I changed this regular VStack to LazyVStack and I no longer saw the 100% memory issues.

Try starting at the sub view where you are loading the image, is this view in a regular Stack or a Lazy stack? if it is in a regular stack then this could be your problem. If it is already in a LazyStack then perhaps my fix will not work for you.

This is where I placed the LazyVStack at first, thinking all the sub views in 'PostRowView' would be loaded lazily.

`LazyVStack(spacing: 1) {
                ForEach(self.homeVM.posts, id: \._id) {post in
                    PostRowView(post: post)
                        .onAppear {
                            homeVM.loadMoreContentIfNeeded(artist: userSession.selectedArtist, currentItem: post)
                        }
                }
                
                if homeVM.isLoadingPage {
                    ProgressView()
                }
            }`


Here is the subView that was causing the problem for me, originally, I was using a regular VStack, but when I changed this sub view to use a LazyVStack as well, it fixed my problem

`struct PostImageContent: View, Equatable {
    
    var imageUrl: String
    @State var uiImage: UIImage?
    
    init(_ imageUrl: String) {
        self.imageUrl = imageUrl
        self.uiImage = URLImage(imageUrl).imageLoader.image
    }
    
    var body: some View {
        LazyVStack(alignment: .leading) {
            let urlImage = URLImage(imageUrl)
            
            NavigationLink(destination: FullscreenPostImageView(uiImage: urlImage.$imageLoader.image)
                            .navigationBarTitle("")
                            .navigationBarHidden(false)) {
                urlImage
                    .aspectRatio(contentMode: .fill)
                    .frame(width: 100, height: 100, alignment: .leading)
                    .clipped()
                    .cornerRadius(7)
            }
            .buttonStyle(PlainButtonStyle())
        }
    }
    
    static func == (lhs: PostImageContent, rhs: PostImageContent) -> Bool {
        return lhs.imageUrl == rhs.imageUrl
    }
}`


Hope this helps.

**Comment by wilg** [comment]
@r3pps Thanks, I'll take a look!

**Comment by LuilliCapellan** [comment]
Facing the same issue, can't use Vstack, since it is a chat messages view, with scrollview and lazyvstack im seeing 100% CPU usage

**Comment by dreampiggy** [comment]
@LuilliCapellan @wilg @r3pps @Jarvey @emerabet 

I found a fix, available in: https://github.com/SDWebImage/SDWebImageSwiftUI/pull/162


This bug is because of SwiftUI 2.0 in iOS 14 changes the behavior:

iOS 13: Any `@Published` property for `@Binding` will not trigger another `updateUIView` callback.  This is why I hack for refreshing using the code here:https://github.com/SDWebImage/SDWebImageSwiftUI/blob/1.5.0/SDWebImageSwiftUI/Classes/AnimatedImage.swift#L231

iOS 14: Any `@Published` property for `@Binding` will always trigger another `updateUIView` callback with a new native UIView instance. So we can not bind the loading status to native UIView instance (sd_imageURL/sd_imageName/sd_imageData), instead I use the imageLoading bindable object for recording.

**Comment by LuilliCapellan** [comment]
Thanks for the update, I delete the .indicator and just added a ProgressView on a ZStack behind the WebImage view, is working fine now

**Comment by dreampiggy** [comment]
Solved by [v2.0.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.0.0)

**Comment by LuilliCapellan** [comment]
The problem is still happening on lazyvsack with foreach and scrollview, WebImage is taking 100+% of cpu, version 2.0

**Comment by dreampiggy** [comment]
> The problem is still happening on lazyvsack with foreach and scrollview, WebImage is taking 100+% of cpu, version 2.0

Can not reproduce in our demo when using this:

```swift
func contentView() -> some View {
        ScrollView {
            LazyVStack {
                ForEach(imageURLs, id: \.self) { url in
                    NavigationLink(destination: DetailView(url: url, animated: self.animated)) {
                        HStack {
                            WebImage(url: URL(string:url), isAnimating: .constant(true))
                            .resizable()
                            /**
                             .placeholder {
                                 Image(systemName: "photo")
                             }
                             */
                            .indicator(.activity)
                            .transition(.fade(duration: 0.5))
                            .scaledToFit()
                            .frame(width: CGFloat(100), height: CGFloat(100), alignment: .center)
                            Text((url as NSString).lastPathComponent)
                        }
                    }
                    .buttonStyle(PlainButtonStyle())
                }
                .onDelete { indexSet in
                    indexSet.forEach { index in
                        self.imageURLs.remove(at: index)
                    }
                }
            }
        }
    }
```

Any other demo ?

**Comment by LuilliCapellan** [comment]
I have the code like that demo that you sent, but not inside a NavigationLink, should I send you the instrument profile that checks the cpu usage? or provide you with code?

**Comment by uschen** [comment]
@dreampiggy this is the call

![image](https://user-images.githubusercontent.com/1828412/110194212-36cb9e80-7dec-11eb-8683-501a9afd7764.png)

**Comment by AndyIbanez** [comment]
I can unfortunately still reproduce this SDWebImageSwiftUI 2.0.2. I have a complex hierarchy with many stacks.

Essentially, I have a ScrollView > LazyVStack > Multiple LazyGridViews > ForEach > Multiple VStacks within each > WebImages in each.

As this is a private app, I cannot share the source code. I will happily try to reproduce it if needed.

**Comment by leogiroux** [comment]
I have the same issue, with a structure like Netflix app with images. Using LazyStack. Normal starck are working great but takes too much time to render since there is a lot of images.

**Comment by long-nguyen** [comment]
I also got this issue when I set the webImage url as @State. For example: 
```
@State var coverUrl: String
            WebImage(url: URL(string: coverUrl)).resizable()
                .placeholder(Image(R.image.no_profile_image.name))
               .indicator(.activity)
                .transition(.fade(duration: 0.5))
                .scaledToFill()
                .frame(width:preferedWidth, height: preferedHeight)
                .clipped()
```
Remove the @State then it works

**Comment by chrysb** [comment]
I'm still seeing this issue in `2.0.0` when the containing view is `.equatable()`. It uses 100% CPU for both `WebImage` and `AnimatedImage`

```
ScrollView {
  LazyVStack {
    ItemView()
      .equatable()
   }
}
```

In this case, the WebImage / Animated Image is a child of ItemView, which is a complex hierarchy of ZStack -> HStack -> VStack.

cc @dreampiggy

**Comment by chrysb** [comment]
I'm not the best with Instruments, but this is the end of the "Heaviest stack trace" when profiling the CPU lockup:

![image](https://user-images.githubusercontent.com/120388/126877052-f1e50cf2-8467-4303-b322-5c44d19653a7.png)

**Comment by JustinMeans** [comment]
I was experiencing this issue even with the 2.0.0 release but was able to get it resolved by changing how my ForEach elements were identified.  The trick for me was to **not** use ForEach(data, id: \.self) and instead use ForEach(data, id: **\.id**) with your data model's ID.

**Comment by twocentstudios** [comment]
I've found a minimal reproduction for what I think is the same bug. 

Running the below will: 

* produce an infinite re-render loop
* pin the CPU usage to 100%
* increase memory usage indefinitely
* freeze the UI

Note that _only_ the `body` of `ImageView` re-renders.

```swift
import SDWebImageSwiftUI
import SwiftUI

@main
struct sdwebimage_App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    var body: some View {
        ScrollView {
            LazyVStack {
                ForEach(1 ..< 5) { idx in
                    VStack {
                        ImageView(url: URL(string: "https://placekitten.com/252/448")!)
                    }
                }
            }
        }
    }
}

struct ImageView: View {
    let url: URL
    @State var anyVar: UIImage?

    var body: some View {
        WebImage(url: url)
    }
}
```

* SDWebImageSwiftUI v2.0.2
* Devices & iOS versions
    * Broken: iPhone Simulator 14.5
    * Broken: iPad Device 14.5.1
    * Broken: iPad Device 14.7.1
    * OK: iPhone Simulator 15.0b4
* `VStack` inside the `ForEach` breaks as `HStack` or `ZStack` too (`Group` does not break).
* URL must be non-nil in order to break.
* `@State` var of any type must be defined within `ImageView` in order to break.
* `1 ..< N` - `N` = as many images as it takes to exceed the screen height
    * e.g. `N = 4` - iPhone 12 Pro
    * e.g. `N = 5` - iPad 9.7

Some example stack traces from manually pausing the debugger (these are different every pause because it's a re-render loop).

* [Example 1 (png)](https://user-images.githubusercontent.com/603478/127960646-37be966d-9851-4dea-8816-b729030db907.png)
* [Example 2 (png)](https://user-images.githubusercontent.com/603478/127960668-6e0040a1-23bd-4010-a642-05308a127991.png)

**Comment by wilg** [comment]
Chiming in without knowing the full details: I don't think it's valid to have `@State var anyVar: UIImage?` as it is a class. Should be wrapped in a ObservableObject and use @StateObject.

**Comment by pwightman** [comment]
It hasn't been my experience that storing classes inside a `@State` causes any problems, I do it in a handful of places and never seen an issue. Worth a try to see if it's related though.

**Comment by wilg** [comment]
`@State` _does not work with classes_ – it will appear to work but reset the state unexpectedly. https://www.hackingwithswift.com/books/ios-swiftui/why-state-only-works-with-structs

**Comment by twocentstudios** [comment]
@wilg Thanks for the heads up. I should have made it clearer in my comment that the type of the `@State var` doesn't matter. It can be `Bool?` or `Bool` or `Int` or `String` and the same problem occurs. I'll change the code in my example so it won't be complicated by that part. 🙏 

As far as class vs. structs, you're right that in the general case I wouldn't expect a class to work with `@State`. I obviously don't know the implementation details of SwiftUI, but my intuition is that since `UIImage` is immutable the specific problem of a `View` not updating when a class's fields change isn't applicable.

**Comment by haitaox** [comment]
any update or plan to fix this issue?

**Comment by pwightman** [comment]
`@State` works identically for structs and classes: when it is assigned a new value, it marks that view as "dirty" and relevant diff/render logic is run. Changing anything in a struct implicitly assigns a new value for the entire struct, which pairs nicely with `@State` and gives desirable behavior.

Classes do not have that same behavior, so it can be confusing that changing values in an object does not cause the view to update (which is what @wilg is referring to).

But to be clear: there is no "undefined behavior" going on, all of `@State`'s semantics hold equally well for both structs and classes: if the var is re-assigned, the view is updated. If you re-assign an object (even the same object) to the `@State` var, you'll see that it updates.

**Comment by abinhho** [comment]
Same issue when wrap image with a button then CPU gets to `100%`, version `2.0.0`

```
Button(action: {
    onSelectPhoto(photo)
}) {
    ImageView(imageURL: photo.imageURL, width: ScreenHelper.width/3, height: ScreenHelper.width/3)
}
```

**Comment by LilaQ** [comment]
This is still an issue, why wasn't this fixed yet? This is really an issue in a lot of configurations and should have high priority imo.

**Comment by dreampiggy** [comment]
Hi.

This is actually my personal maintained project from the beginning (not like SDWebImage Core, which maintained by at least 10+ people). And like the annocement in SDWebImage, I'll quit the SDWebImage org maintainess and iOS development scope (focus on Swift language toolchain and LLVM staff)

And I used to think this issue already been fixed by v2.2.0

If you think this issue is still exists, please:

### Provide the real demo (not simple code snippet) for me to debug and investigate.

Or I can not provide any extra help.
